"use client";

import { useLanguage } from "@/shared/providers/language-context";

const vi = {
  pageTitle: "Bảng xếp hạng",
  pageSub: "Cùng luyện tập, cải thiện kỹ năng phỏng vấn và chinh phục thứ hạng cao hơn.",
  season: "Mùa hiện tại · Tuần 34",
  tabsAria: "Chế độ xếp hạng",
  tabTotalXp: "Tổng XP",
  tabStreak: "Chuỗi ngày",
  tabWeekly: "Tuần này",
  bannerTitle: "Chinh phục phỏng vấn, vươn lên dẫn đầu!",
  bannerSub: "Luyện tập đều đặn mỗi ngày - Tích lũy XP - Thăng hạng liên đoàn",
  bannerXp: "+100 XP / phiên",
  faqTitle: "Câu hỏi thường gặp",
  faq: [
    { q: "Bảng xếp hạng được tính như thế nào?", a: "XP được tích lũy từ các phiên luyện tập, kết quả phỏng vấn thử, chuỗi luyện tập hàng ngày và tiến độ lộ trình học. Tổng XP quyết định thứ hạng dài hạn, còn tab Tuần này chỉ tính XP kiếm được trong 7 ngày gần nhất." },
    { q: "Làm sao để kiếm thêm XP?", a: "Hoàn thành phiên luyện tập (+100 XP), đạt điểm cao: ≥70 (+20 XP), ≥80 (+40 XP), ≥90 (+70 XP bonus); duy trì chuỗi hàng ngày (+10 XP/ngày); hoàn thành thử thách tuần và tiến trình lộ trình (+50 XP)." },
    { q: "Chuỗi luyện tập được tính như thế nào?", a: "Bạn cần hoàn thành ít nhất 1 phiên luyện tập mỗi ngày để duy trì chuỗi. Bỏ qua 1 ngày sẽ mất chuỗi. Chuỗi được tính theo ngày dương lịch (00:00-23:59 giờ Việt Nam)." },
    { q: "Khi nào bảng xếp hạng và liên đoàn được reset?", a: "Bảng xếp hạng tuần và liên đoàn làm mới vào 00:00 UTC Thứ Hai mỗi tuần. XP tổng và chuỗi ngày không bị reset - chỉ XP tuần về 0 mỗi chu kỳ mới." },
    { q: "XP có ảnh hưởng đến kết quả tuyển dụng không?", a: "Không. XP và bảng xếp hạng chỉ phục vụ mục đích luyện tập và tạo động lực cá nhân. Đây không phải điểm tuyển dụng chính thức và không được chia sẻ với nhà tuyển dụng." },
  ],
  days: "ngày",
  you: "Bạn",
  level: "Cấp",
  sessions: "phiên",
  colRank: "Hạng",
  colCandidate: "Ứng viên",
  colSessions: "Phiên",
  colScore: "Điểm",
  yourPosition: "vị trí của bạn",
  collapse: "Thu gọn",
  seeMore: "Xem thêm",
  top3Aria: "Top 3 ứng viên",
  yourInfo: "Thông tin của bạn",
  yourRank: "Hạng của bạn",
  thisWeek: "tuần này",
  needMore: "Cần thêm",
  toPass: "để vượt hạng",
  viewProgress: "Xem chi tiết tiến độ",
  yourStats: "Thành tích của bạn",
  statTotalXp: "Tổng XP",
  statLevel: "Cấp độ hiện tại",
  statWeekRank: "Hạng tuần này",
  statWeekXp: "XP tuần này",
  featured: "Thành tích nổi bật",
  achXp: "5.420 XP tích lũy",
  achStreak: "Chuỗi 3 ngày",
  achSessions: "53 phiên hoàn thành",
  achRank: "+2 hạng tuần này",
  leagues: ["Đồng", "Bạc", "Vàng", "Bạch kim", "Kim cương"],
  leagueLetters: ["Đ", "B", "V", "Pt", "KS"],
  league: "Liên đoàn",
  leagueRank: "hạng #7 / 30 trong liên đoàn của bạn",
  promote: "Top 5 tuần này sẽ thăng lên",
  topInLeague: "Top trong liên đoàn của bạn",
  challengesTitle: "Thi đua luyện tập mỗi tuần",
  challenges: [
    "Bảng xếp hạng biến việc luyện tập phỏng vấn thành một cuộc thi nhẹ nhàng và đầy động lực. Mỗi tuần, top ứng viên có XP cao nhất được vinh danh, nhờ đó bạn có thêm lý do để luyện tập đều đặn thay vì để kỹ năng bị mai một.",
    "Bên cạnh bảng xếp hạng tuần, HireGen còn có hệ thống liên đoàn từ Đồng, Bạc, Vàng, Bạch kim đến Kim cương. Bạn thi đua với những người cùng bậc - nhóm dẫn đầu thăng hạng lên liên đoàn cao hơn, còn nhóm cuối bảng có thể rớt xuống - một vòng cạnh tranh công bằng và hấp dẫn.",
    "Mọi hoạt động luyện tập đều cộng XP: hoàn thành phiên thử, đạt điểm cao, duy trì chuỗi hàng ngày hay hoàn thành lộ trình. Bảng và liên đoàn reset vào 00:00 UTC Thứ Hai mỗi tuần, nên ai cũng có cơ hội làm lại từ đầu. Hãy biến áp lực thi đua thành thói quen luyện tập phỏng vấn mỗi ngày.",
  ],
  numberLocale: "vi-VN",
};

const en: typeof vi = {
  pageTitle: "Leaderboard",
  pageSub: "Practice together, sharpen your interview skills and climb higher in the rankings.",
  season: "Current season · Week 34",
  tabsAria: "Ranking mode",
  tabTotalXp: "Total XP",
  tabStreak: "Streak",
  tabWeekly: "This week",
  bannerTitle: "Ace your interviews and climb to the top!",
  bannerSub: "Practice every day - Earn XP - Move up the leagues",
  bannerXp: "+100 XP / session",
  faqTitle: "Frequently asked questions",
  faq: [
    { q: "How is the leaderboard calculated?", a: "XP comes from practice sessions, mock interview results, your daily practice streak and learning roadmap progress. Total XP decides the long-term ranking, while the This week tab only counts XP earned in the last 7 days." },
    { q: "How do I earn more XP?", a: "Complete a practice session (+100 XP), score high: 70+ (+20 XP), 80+ (+40 XP), 90+ (+70 XP bonus), keep your daily streak (+10 XP/day), and finish weekly challenges and roadmap steps (+50 XP)." },
    { q: "How is the practice streak counted?", a: "You need to complete at least 1 practice session every day to keep the streak. Skipping a day resets it. Days follow the calendar day (00:00-23:59 Vietnam time)." },
    { q: "When do the leaderboard and leagues reset?", a: "The weekly leaderboard and leagues refresh at 00:00 UTC every Monday. Total XP and streak are not reset - only weekly XP returns to 0 each cycle." },
    { q: "Does XP affect hiring results?", a: "No. XP and the leaderboard exist only for practice and personal motivation. They are not an official hiring score and are not shared with recruiters." },
  ],
  days: "days",
  you: "You",
  level: "Level",
  sessions: "sessions",
  colRank: "Rank",
  colCandidate: "Candidate",
  colSessions: "Sessions",
  colScore: "Score",
  yourPosition: "your position",
  collapse: "Show less",
  seeMore: "Show more",
  top3Aria: "Top 3 candidates",
  yourInfo: "Your standing",
  yourRank: "Your rank",
  thisWeek: "this week",
  needMore: "You need",
  toPass: "more to pass rank",
  viewProgress: "View progress details",
  yourStats: "Your achievements",
  statTotalXp: "Total XP",
  statLevel: "Current level",
  statWeekRank: "Rank this week",
  statWeekXp: "XP this week",
  featured: "Featured achievements",
  achXp: "5,420 XP earned",
  achStreak: "3-day streak",
  achSessions: "53 sessions completed",
  achRank: "+2 places this week",
  leagues: ["Bronze", "Silver", "Gold", "Platinum", "Diamond"],
  leagueLetters: ["Br", "S", "G", "Pt", "D"],
  league: "League",
  leagueRank: "rank #7 / 30 in your league",
  promote: "Top 5 this week will be promoted to",
  topInLeague: "Top of your league",
  challengesTitle: "Weekly practice competition",
  challenges: [
    "The leaderboard turns interview practice into a light, motivating competition. Every week the candidates with the most XP are recognised, giving you one more reason to practise regularly instead of letting your skills fade.",
    "Besides the weekly leaderboard, HireGen has a league system from Bronze, Silver, Gold and Platinum to Diamond. You compete with people at the same level - the leaders move up to a higher league and the bottom of the table can drop down - a fair and engaging cycle of competition.",
    "Every practice activity earns XP: completing a mock session, scoring high, keeping your daily streak or finishing your roadmap. The leaderboard and leagues reset at 00:00 UTC every Monday, so everyone gets a fresh start. Turn competitive pressure into a daily interview practice habit.",
  ],
  numberLocale: "en-US",
};

export function useLeaderboardText() {
  const { lang } = useLanguage();
  return lang === "vi" ? vi : en;
}
