import type { CoachJob } from "@/features/candidate/services/coach.service";

export const COACH_JOB_LS_KEY = "cand_coach_job";
export const COACH_JOB_EVENT = "cand:coach-job-updated";

/** Separate, long-lived key that accumulates every question-set ID generated by
 *  AI Coach.  Unlike COACH_JOB_LS_KEY it is never cleared — used to suppress
 *  the marketplace feedback-rating dialog for coach-generated sets. */
const COACH_SET_IDS_KEY = "cand_coach_set_ids";

export type CoachJobEntry = {
  id: string;
  purpose?: string;
  status: string;
  questionSetId?: string | null;
  errorMessage?: string | null;
};

export function readCoachJobEntry(): CoachJobEntry | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(COACH_JOB_LS_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as CoachJobEntry;
    return parsed?.id ? parsed : null;
  } catch {
    return null;
  }
}

/** Persist a question-set ID generated by AI Coach so it can be looked up
 *  later even after the active coach job entry has been cleared. */
export function addCoachGeneratedSetId(questionSetId: string) {
  if (typeof window === "undefined") return;
  try {
    const raw = localStorage.getItem(COACH_SET_IDS_KEY);
    const ids: string[] = raw ? (JSON.parse(raw) as string[]) : [];
    if (!ids.includes(questionSetId)) {
      ids.push(questionSetId);
      localStorage.setItem(COACH_SET_IDS_KEY, JSON.stringify(ids));
    }
  } catch { /* ignore */ }
}

/** Returns true when the given question-set ID was generated by AI Coach. */
export function isCoachGeneratedSetId(questionSetId: string): boolean {
  if (typeof window === "undefined") return false;
  try {
    const raw = localStorage.getItem(COACH_SET_IDS_KEY);
    if (!raw) return false;
    return (JSON.parse(raw) as string[]).includes(questionSetId);
  } catch {
    return false;
  }
}

export function writeCoachJobEntry(entry: CoachJobEntry | null) {
  if (typeof window === "undefined") return;
  if (!entry) {
    localStorage.removeItem(COACH_JOB_LS_KEY);
  } else {
    localStorage.setItem(COACH_JOB_LS_KEY, JSON.stringify(entry));
    // Auto-persist any question-set ID to the long-lived coach set registry so
    // we can still identify it after the active job entry is cleared.
    if (entry.questionSetId) addCoachGeneratedSetId(entry.questionSetId);
  }
  window.dispatchEvent(new CustomEvent(COACH_JOB_EVENT));
}

export function registerCoachJob(job: CoachJob) {
  writeCoachJobEntry({
    id: job.id,
    purpose: job.purpose,
    status: job.status,
    questionSetId: job.questionSetId ?? null,
    errorMessage: job.errorMessage ?? null,
  });
}

export function clearCoachJob() {
  writeCoachJobEntry(null);
}
